spring:
  profiles:
    active: dev
  # 数据源，使用阿里巴巴的druid数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: nies
      password: nies123
      url: jdbc:mysql://localhost:3306/toxicitypred?useSSL=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      # 连接池配置
      initialSize: 5  # 初始化大小
      minIdle: 5      # 最小
      maxActive: 20   # 最大
      maxWait: 60000  # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 30000     # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true          # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j2              # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #useGlobalDataSourceStat: true        # 合并多个DruidDataSource的监控数据
      # 监控统计
      filter:
        stat:
          enabled: true
          log-slow-sql: true                # 打印慢sql
          slow-sql-millis: 200              # 超过200毫秒即为慢sql
        #log4j2:
          #statement-log-enabled: true
          #result-set-log-enabled: true
          #statement-executable-sql-log-enable: true
      # Druid WebStatFilter配置（数据库连接池监控统计插件）
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
      # Druid StatViewServlet配置（数据库连接池监控页面插件）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:
  # 异常处理
  mvc:
    throw-exception-if-no-handler-found: true # 异常处理
# mybatis配置
mybatis:
  type-aliases-package: cn.edu.nwafu.cie.toxicitypre.entities
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
# 分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql









#######################原生的数据库连接(JDBC)#######################
#spring.datasource.url=jdbc:mysql://210.27.82.153:3306/toxicitypred?useSSL=false&useUnicode=true&characterEncoding=utf8
#spring.datasource.username=nies
#spring.datasource.password=nies123
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

########################c3p0的数据库连接(Java类配置，mybatisC3P0)#######################
#jdbc.driver=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://210.27.82.153:3306/toxicitypred?useSSL=false&useUnicode=true&characterEncoding=utf8
#jdbc.username=nies
#jdbc.password=nies123

#######################原生的mybatis配置方式#######################
#mapper_path=/mapper/**.xml
#entity_package=cn.edu.nwafu.cie.toxicitypred.entities
#mybatis_config_file=mybatis-config.xml